# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: c-cpp-build-macos
'on':
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  c-cpp-build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          brew update
          brew upgrade
          brew install autoconf automake libtool tcl-tk libpcap
      - name: Configure and build
        run: |
          ./autogen.sh
          ./configure
          make
      - name: Get properties from configure.ac
        id: props
        shell: bash
        run: |
          name=$(grep AC_INIT configure.ac | sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p')
          echo "name=$name" >> $GITHUB_OUTPUT
          version=$(grep AC_INIT configure.ac | sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create source package
        run: |
          make dist
      - name: Create binary package
        run: |
          make binary-dist
      - name: Prepare packages to distribution
        run: |
          mkdir -p dist
          mv "${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}.tar.gz" \
            "dist/${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-source.tar.gz"
          mv "${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-bin.tar.gz" \
            "dist/${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-linux.tar.gz"
      - name: Detect act
        id: act
        run: |
          echo "running=${ACT:-false}" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        if: ${{ steps.act.outputs.running != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
