# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: c-cpp-build-linux
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  c-cpp-build-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y build-essential pkg-config libpcap-dev \
            tcl-dev &&
          wget https://ftp.gnu.org/gnu/automake/automake-1.18.tar.gz &&
          tar xvfz automake-1.18.tar.gz &&
          cd automake-1.18 &&
          ./configure &&
          make &&
          sudo make install
      - name: Configure and build
        run: |
          ./configure
          make
